"""MERAS flowcharts 13-22: the administrator features (dashboard, inventory, POS, inquiries, reports, ...)."""
from flowchart_registry import chart, entry


def back_to_portal(c, prev, row, prev_label="No"):
    """Closing 'Back to Admin Portal?' decision shared by every admin chart."""
    c.dec("d_back", "Back to Admin Portal?", 0, row)
    c.off("AA", "AA", 1, row)
    c.e(prev, "d_back", prev_label)
    c.e("d_back", "AA", "Yes", out="r", into="l")
    c.conn("k_end", "1", 0, row + 1.4)
    c.e("d_back", "k_end", "No")


# -------------------------------------------------------------------------- 13
@chart("13-dashboard", "Flowchart 13. Dashboard (BA)", cw=300, rh=150)
def dashboard(c):
    entry(c, "BA", 'Load "Dashboard" Page')
    c.proc("calc", "Compute Daily, Weekly and Monthly Sales, Total Revenue, Total Products and Low-Stock Count", 0, 3.3)
    c.db("db", "sales_db\nsale_items_db\nproducts_db", 1, 3.3)
    c.e("view", "calc")
    c.e("db", "calc", out="l", into="r")
    c.proc("show", "Display Summary Cards, 7-Day Sales Trend, Top Products, Stock by Category, Recent Sales and Low-Stock List", 0, 5.2)
    c.e("calc", "show")
    c.dec("d_low", "View Low-Stock Item?", 0, 7.1)
    c.off("BC", "BC", 1, 7.1)
    c.e("show", "d_low")
    c.e("d_low", "BC", "Yes", out="r", into="l")
    c.dec("d_rep", "View Sales Report?", 0, 8.6)
    c.off("BE", "BE", 1, 8.6)
    c.e("d_low", "d_rep", "No")
    c.e("d_rep", "BE", "Yes", out="r", into="l")
    back_to_portal(c, "d_rep", 10.1)


# -------------------------------------------------------------------------- 14
@chart("14-inventory", "Flowchart 14. Inventory (BC)", cw=300, rh=150)
def inventory(c):
    entry(c, "BC", 'Load "Inventory" Page')
    c.db("dbv", "products_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    # search
    c.dec("d1", "Search Product?", 0, 3.2)
    c.io("s1", "Input Name, SKU or Category", 1, 3.2)
    c.proc("s2", "Display Matching Products", 2, 3.2)
    c.conn("s3", "1", 3, 3.2)
    c.e("view", "d1")
    c.e("d1", "s1", "Yes", out="r", into="l")
    c.e("s1", "s2", out="r", into="l")
    c.e("s2", "s3", out="r", into="l")
    # add / edit
    c.conn("c2", "2", 1, 4.0)
    c.dec("d2", "Add or Edit Product?", 0, 4.9)
    c.io("a1", "Input Name, SKU, Unit, Category, Price, Bulk Price and Quantity", 1, 4.9)
    c.dec("a2", "Details Valid?", 2, 4.9)
    c.db("a3", "products_db", 3, 4.9)
    c.act("a4", "Save Product; Record Activity Log", 3, 6.5)
    c.conn("a5", "1", 3, 7.7)
    c.proc("a6", "Display Validation Error", 2, 6.5)
    c.conn("a7", "2", 2, 7.7)
    c.e("d1", "d2", "No")
    c.e("c2", "a1")
    c.e("d2", "a1", "Yes", out="r", into="l")
    c.e("a1", "a2", out="r", into="l")
    c.e("a2", "a3", "Yes", out="r", into="l")
    c.e("a3", "a4")
    c.e("a4", "a5")
    c.e("a2", "a6", "No")
    c.e("a6", "a7")
    # delete
    c.dec("d3", "Delete Product?", 0, 8.6)
    c.dec("x1", "Confirm Delete?", 1, 8.6)
    c.db("x2", "products_db", 2, 8.6)
    c.act("x3", "Delete Record; Record Activity Log", 3, 8.6)
    c.conn("x4", "1", 3, 9.9)
    c.conn("x5", "1", 1, 9.9)
    c.e("d2", "d3", "No")
    c.e("d3", "x1", "Yes", out="r", into="l")
    c.e("x1", "x2", "Yes", out="r", into="l")
    c.e("x2", "x3", out="r", into="l")
    c.e("x3", "x4")
    c.e("x1", "x5", "No")
    # import
    c.dec("d4", "Import Products from CSV?", 0, 10.8)
    c.off("BC2", "BC2", 1, 10.8)
    c.e("d3", "d4", "No")
    c.e("d4", "BC2", "Yes", out="r", into="l")
    back_to_portal(c, "d4", 12.3)


# -------------------------------------------------------------------------- 15
@chart("15-import-csv", "Flowchart 15. Import Products from CSV (BC2)", cw=300, rh=150)
def import_csv(c):
    entry(c, "BC2", 'View "Import Products" Dialog')
    c.io("inp", "Upload CSV File (name, price, quantity, unit)", 0, 3.2)
    c.e("view", "inp")
    c.dec("d_ok", "File Valid? (CSV, up to 2 MB, Required Columns)", 0, 4.9)
    c.e("inp", "d_ok")
    c.proc("err", "Display Import Errors", 1, 4.9)
    c.off("BC", "BC", 2, 4.9)
    c.e("d_ok", "err", "No", out="r", into="l")
    c.e("err", "BC", out="r", into="l")
    c.dec("d_ex", "Product Name Already Exists?", 0, 6.6)
    c.e("d_ok", "d_ex", "Yes")
    c.proc("upd", "Update Existing Product (Keep its SKU)", 1, 6.6)
    c.e("d_ex", "upd", "Yes", out="r", into="l")
    c.proc("new", "Create Product (Generate SKU from Name)", 0, 8.2)
    c.e("d_ex", "new", "No")
    c.db("db", "products_db", 0, 9.8)
    c.e("new", "db")
    c.e("upd", "db", out="b", into="r")
    c.act("save", "Save Imported Rows; Record Activity Log", 1, 9.8)
    c.e("db", "save", out="r", into="l")
    c.proc("sum", "Display Import Summary (Rows Imported / Skipped)", 1, 11.4)
    c.e("save", "sum")
    c.off("out", "BC", 1, 12.8)
    c.e("sum", "out")


# -------------------------------------------------------------------------- 16
@chart("16-pos-cart", "Flowchart 16. Point of Sale: Build the Cart (BB)", cw=300, rh=150)
def pos(c):
    entry(c, "BB", 'Load "Point of Sale" Page')
    c.db("dbv", "products_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    c.dec("d1", "Search Product?", 0, 3.2)
    c.io("s1", "Input Product Name or SKU", 1, 3.2)
    c.proc("s2", "Display Matching Products", 2, 3.2)
    c.conn("s3", "1", 3, 3.2)
    c.e("view", "d1")
    c.e("d1", "s1", "Yes", out="r", into="l")
    c.e("s1", "s2", out="r", into="l")
    c.e("s2", "s3", out="r", into="l")
    c.dec("d2", "Add Item to Cart?", 0, 4.9)
    c.dec("st", "Stock Available?", 1, 4.9)
    c.proc("add", "Add Item to Cart (Bulk Price when Minimum Quantity is Reached)", 2, 4.9)
    c.conn("ak", "1", 3, 4.9)
    c.proc("oos", 'Display "Product is out of stock!"', 1, 6.4)
    c.conn("ok", "1", 2, 6.4)
    c.e("d1", "d2", "No")
    c.e("d2", "st", "Yes", out="r", into="l")
    c.e("st", "add", "Yes", out="r", into="l")
    c.e("add", "ak", out="r", into="l")
    c.e("st", "oos", "No")
    c.e("oos", "ok", out="r", into="l")
    c.dec("d3", "Update Cart?", 0, 8.0)
    c.proc("u1", "Increase / Decrease Quantity, Remove Item or Clear Cart", 1, 8.0)
    c.conn("uk", "1", 2, 8.0)
    c.e("d2", "d3", "No")
    c.e("d3", "u1", "Yes", out="r", into="l")
    c.e("u1", "uk", out="r", into="l")
    c.dec("d4", "Checkout?", 0, 9.6)
    c.off("BB2", "BB2", 1, 9.6)
    c.e("d3", "d4", "No")
    c.e("d4", "BB2", "Yes", out="r", into="l")
    back_to_portal(c, "d4", 11.1)


# -------------------------------------------------------------------------- 17
@chart("17-pos-checkout", "Flowchart 17. Point of Sale: Checkout and Receipt (BB2)", cw=300, rh=150)
def checkout(c):
    entry(c, "BB2", "View Cart and Grand Total")
    c.dec("d_e", "Cart Empty?", 0, 3.2)
    c.e("view", "d_e")
    c.proc("emp", 'Display "Cart is empty!"', 1, 3.2)
    c.off("BB", "BB", 2, 3.2)
    c.e("d_e", "emp", "Yes", out="r", into="l")
    c.e("emp", "BB", out="r", into="l")
    c.conn("c2", "2", -1, 4.0)
    c.io("inp", "Select Payment Method (Cash / GCash) and Input Cash Tendered", 0, 4.9)
    c.e("d_e", "inp", "No")
    c.e("c2", "inp", out="r", into="t")
    c.dec("d_pay", "Payment Sufficient? (GCash or Cash >= Total)", 0, 6.6)
    c.e("inp", "d_pay")
    c.proc("err", 'Display "Insufficient cash tendered."', 1, 6.6)
    c.conn("c2b", "2", 2, 6.6)
    c.e("d_pay", "err", "No", out="r", into="l")
    c.e("err", "c2b", out="r", into="l")
    c.db("db", "sales_db\nsale_items_db\nproducts_db", 0, 8.4)
    c.e("d_pay", "db", "Yes")
    c.act("save", "Save Sale and Items; Deduct Stock; Record Activity Log", 1, 8.4)
    c.e("db", "save", out="r", into="l")
    c.proc("rec", "Compute Change; Display Receipt", 1, 10.0)
    c.e("save", "rec")
    c.dec("d_pr", "Print Receipt?", 1, 11.5)
    c.e("rec", "d_pr")
    c.proc("pr", "Print Receipt (Sale Number, Items, Total, Cash, Change)", 2, 11.5)
    c.e("d_pr", "pr", "Yes", out="r", into="l")
    c.off("out", "BB", 1, 13.2)
    c.e("d_pr", "out", "No")
    c.e("pr", "out", out="b", into="r")


# -------------------------------------------------------------------------- 18
@chart("18-inquiries", "Flowchart 18. Customer Inquiries (BD)", cw=300, rh=150)
def inquiries(c):
    entry(c, "BD", 'Load "Customer Inquiries" Page')
    c.db("dbv", "inquiries_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    # search / filter
    c.dec("d1", "Search or Filter by Status?", 0, 3.2)
    c.io("s1", "Input Keyword or Select Status (All / Pending / Responded)", 1, 3.2)
    c.proc("s2", "Display Matching Inquiries", 2, 3.2)
    c.conn("s3", "1", 3, 3.2)
    c.e("view", "d1")
    c.e("d1", "s1", "Yes", out="r", into="l")
    c.e("s1", "s2", out="r", into="l")
    c.e("s2", "s3", out="r", into="l")
    # respond
    c.conn("c2", "2", 1, 4.0)
    c.dec("d2", "Respond to Inquiry?", 0, 4.9)
    c.io("r1", "Input Response Message", 1, 4.9)
    c.dec("r2", "Response Valid?", 2, 4.9)
    c.db("r3", "inquiries_db", 3, 4.9)
    c.act("r4", 'Save Response; Mark "Responded"; Record Log', 3, 6.5)
    c.proc("r5", "Send Email Notification to Customer", 3, 8.1)
    c.proc("r6", "Send Push Notification (if Push Token Exists)", 3, 9.6)
    c.conn("r7", "1", 3, 10.8)
    c.proc("re", "Display Validation Error", 2, 6.5)
    c.conn("rk", "2", 2, 7.7)
    c.e("d1", "d2", "No")
    c.e("c2", "r1")
    c.e("d2", "r1", "Yes", out="r", into="l")
    c.e("r1", "r2", out="r", into="l")
    c.e("r2", "r3", "Yes", out="r", into="l")
    c.e("r3", "r4")
    c.e("r4", "r5")
    c.e("r5", "r6")
    c.e("r6", "r7")
    c.e("r2", "re", "No")
    c.e("re", "rk")
    # toggle status
    c.dec("d3", "Change Status? (Pending / Responded)", 0, 8.6)
    c.proc("t1", "Toggle Inquiry Status; Record Activity Log", 1, 8.6)
    c.conn("t2", "1", 1, 9.9)
    c.e("d2", "d3", "No")
    c.e("d3", "t1", "Yes", out="r", into="l")
    c.e("t1", "t2")
    # delete
    c.dec("d4", "Delete Inquiry?", 0, 12.1)
    c.dec("x1", "Confirm Delete?", 1, 12.1)
    c.db("x2", "inquiries_db", 2, 12.1)
    c.act("x3", "Delete Record; Record Activity Log", 3, 12.1)
    c.conn("x4", "1", 3, 13.4)
    c.conn("x5", "1", 1, 13.4)
    c.e("d3", "d4", "No")
    c.e("d4", "x1", "Yes", out="r", into="l")
    c.e("x1", "x2", "Yes", out="r", into="l")
    c.e("x2", "x3", out="r", into="l")
    c.e("x3", "x4")
    c.e("x1", "x5", "No")
    back_to_portal(c, "d4", 14.3)


# -------------------------------------------------------------------------- 19
@chart("19-reports", "Flowchart 19. Sales Reports (BE)", cw=300, rh=150)
def reports(c):
    entry(c, "BE", 'Load "Reports" Page (Default: All Time)')
    c.db("dbv", "sales_db\nsale_items_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    c.dec("d1", "Select Report Period?", 0, 3.3)
    c.io("p1", "Select Period (Weekly / Monthly / Yearly / All Time)", 1, 3.3)
    c.proc("p2", "Compute Revenue, Transactions, Average Sale and Product Breakdown", 2, 3.3)
    c.proc("p3", "Display Report Summary, Product Breakdown and Recent Transactions", 2, 4.9)
    c.conn("p4", "1", 2, 6.1)
    c.e("view", "d1")
    c.e("d1", "p1", "Yes", out="r", into="l")
    c.e("p1", "p2", out="r", into="l")
    c.e("p2", "p3")
    c.e("p3", "p4")
    c.dec("d2", "Export Report to CSV?", 0, 5.0)
    c.proc("x1", "Generate CSV (Summary, Product Breakdown, Transactions)", 1, 5.0)
    c.act("x2", "Download CSV File", 1, 6.5)
    c.conn("x3", "1", 1, 7.7)
    c.e("d1", "d2", "No")
    c.e("d2", "x1", "Yes", out="r", into="l")
    c.e("x1", "x2")
    c.e("x2", "x3")
    c.dec("d3", "Print Report?", 0, 8.4)
    c.proc("pr", "Open Browser Print Dialog", 1, 8.4)
    c.conn("pk", "1", 2, 8.4)
    c.e("d2", "d3", "No")
    c.e("d3", "pr", "Yes", out="r", into="l")
    c.e("pr", "pk", out="r", into="l")
    back_to_portal(c, "d3", 10.0)


# -------------------------------------------------------------------------- 20
@chart("20-users", "Flowchart 20. User Management (BF)", cw=300, rh=150)
def users(c):
    entry(c, "BF", 'Load "User Management" Page')
    c.db("dbv", "users_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    c.dec("d1", "Search User?", 0, 3.2)
    c.io("s1", "Input Name or Email", 1, 3.2)
    c.proc("s2", "Display Matching Users", 2, 3.2)
    c.conn("s3", "1", 3, 3.2)
    c.e("view", "d1")
    c.e("d1", "s1", "Yes", out="r", into="l")
    c.e("s1", "s2", out="r", into="l")
    c.e("s2", "s3", out="r", into="l")
    # add user
    c.conn("c2", "2", 1, 4.0)
    c.dec("d2", "Add User?", 0, 4.9)
    c.io("a1", "Input Name, Email, Password and Role", 1, 4.9)
    c.dec("a2", "Valid, Unique Email and Role Allowed?", 2, 4.9)
    c.db("a3", "users_db", 3, 4.9)
    c.act("a4", "Save User; Record Activity Log", 3, 6.5)
    c.conn("a5", "1", 3, 7.7)
    c.proc("a6", "Display Error (e.g. Only One Administrator Allowed)", 2, 6.5)
    c.conn("a7", "2", 2, 7.7)
    c.e("d1", "d2", "No")
    c.e("c2", "a1")
    c.e("d2", "a1", "Yes", out="r", into="l")
    c.e("a1", "a2", out="r", into="l")
    c.e("a2", "a3", "Yes", out="r", into="l")
    c.e("a3", "a4")
    c.e("a4", "a5")
    c.e("a2", "a6", "No")
    c.e("a6", "a7")
    # change role
    c.dec("d3", "Change Role?", 0, 8.8)
    c.io("r1", "Select New Role (Customer / Admin)", 1, 8.8)
    c.dec("r2", "Allowed? (Not Own Account, Single Admin)", 2, 8.8)
    c.db("r3", "users_db", 3, 8.8)
    c.act("r4", "Update Role; Record Activity Log", 3, 10.4)
    c.conn("r5", "1", 3, 11.6)
    c.proc("r6", "Display Error Message", 2, 10.4)
    c.conn("r7", "1", 2, 11.6)
    c.e("d2", "d3", "No")
    c.e("d3", "r1", "Yes", out="r", into="l")
    c.e("r1", "r2", out="r", into="l")
    c.e("r2", "r3", "Yes", out="r", into="l")
    c.e("r3", "r4")
    c.e("r4", "r5")
    c.e("r2", "r6", "No")
    c.e("r6", "r7")
    # delete user
    c.dec("d4", "Delete User?", 0, 12.6)
    c.dec("x1", "Own Account?", 1, 12.6)
    c.proc("x2", 'Display "You cannot delete yourself!"', 2, 12.6)
    c.conn("x3", "1", 3, 12.6)
    c.db("x4", "users_db", 1, 14.1)
    c.act("x5", "Delete User; Record Activity Log", 2, 14.1)
    c.conn("x6", "1", 3, 14.1)
    c.e("d3", "d4", "No")
    c.e("d4", "x1", "Yes", out="r", into="l")
    c.e("x1", "x2", "Yes", out="r", into="l")
    c.e("x2", "x3", out="r", into="l")
    c.e("x1", "x4", "No")
    c.e("x4", "x5", out="r", into="l")
    c.e("x5", "x6", out="r", into="l")
    back_to_portal(c, "d4", 15.3)


# -------------------------------------------------------------------------- 21
@chart("21-settings", "Flowchart 21. System Settings (BG)", cw=300, rh=150)
def settings(c):
    entry(c, "BG", 'Load "Settings" Page (System Overview)')
    # change password
    c.conn("c2", "2", 1, 2.35)
    c.dec("d1", "Change Admin Password?", 0, 3.2)
    c.io("p1", "Input Current, New and Confirm Password", 1, 3.2)
    c.dec("p2", "Current Password Correct and New Password Valid?", 2, 3.2)
    c.db("p3", "users_db", 3, 3.2)
    c.act("p4", "Save New Password (Hashed); Record Log", 3, 4.9)
    c.conn("p5", "1", 3, 6.1)
    c.proc("p6", "Display Error Message", 2, 4.9)
    c.conn("p7", "1", 2, 6.1)
    c.e("view", "d1")
    c.e("c2", "p1")
    c.e("d1", "p1", "Yes", out="r", into="l")
    c.e("p1", "p2", out="r", into="l")
    c.e("p2", "p3", "Yes", out="r", into="l")
    c.e("p3", "p4")
    c.e("p4", "p5")
    c.e("p2", "p6", "No")
    c.e("p6", "p7")
    # export
    c.dec("d2", "Export Data to CSV?", 0, 6.9)
    c.io("e1", "Select Data (All, Products, Sales, Inquiries, Users...)", 1, 6.9)
    c.act("e2", "Download CSV File", 2, 6.9)
    c.conn("e3", "1", 3, 6.9)
    c.e("d1", "d2", "No")
    c.e("d2", "e1", "Yes", out="r", into="l")
    c.e("e1", "e2", out="r", into="l")
    c.e("e2", "e3", out="r", into="l")
    # maintenance actions
    c.dec("d3", "Run Maintenance Action?", 0, 8.6)
    c.io("m1", "Select Action (Clear Sales, Clear Chat, Load Demo Inventory)", 1, 8.6)
    c.dec("m2", "Confirm Action?", 2, 8.6)
    c.db("m3", "sales_db\nmessages_db\nproducts_db", 3, 8.6)
    c.act("m4", "Execute Action; Record Activity Log", 3, 10.4)
    c.conn("m5", "1", 3, 11.6)
    c.conn("m6", "1", 2, 10.0)
    c.e("d2", "d3", "No")
    c.e("d3", "m1", "Yes", out="r", into="l")
    c.e("m1", "m2", out="r", into="l")
    c.e("m2", "m3", "Yes", out="r", into="l")
    c.e("m3", "m4")
    c.e("m4", "m5")
    c.e("m2", "m6", "No")
    back_to_portal(c, "d3", 12.2)


# -------------------------------------------------------------------------- 22
@chart("22-activity-logs", "Flowchart 22. Activity Logs (BH)", cw=300, rh=150)
def logs(c):
    entry(c, "BH", 'Load "Activity Logs" Page')
    c.db("dbv", "activity_logs_db", 1, 1.7)
    c.e("dbv", "view", out="l", into="r")
    c.proc("show", "Display Log Metrics and Latest Entries (6 per Page)", 0, 3.3)
    c.e("view", "show")
    c.dec("d1", "Filter by Role? (All / Admin / Customer / Guest)", 0, 5.0)
    c.io("f1", "Select Role Filter", 1, 5.0)
    c.proc("f2", "Display Filtered Logs", 2, 5.0)
    c.conn("f3", "1", 3, 5.0)
    c.e("show", "d1")
    c.e("d1", "f1", "Yes", out="r", into="l")
    c.e("f1", "f2", out="r", into="l")
    c.e("f2", "f3", out="r", into="l")
    c.dec("d2", "Search Logs?", 0, 6.7)
    c.io("q1", "Input Name, Action, Description or IP Address", 1, 6.7)
    c.proc("q2", "Display Matching Logs", 2, 6.7)
    c.conn("q3", "1", 3, 6.7)
    c.e("d1", "d2", "No")
    c.e("d2", "q1", "Yes", out="r", into="l")
    c.e("q1", "q2", out="r", into="l")
    c.e("q2", "q3", out="r", into="l")
    c.dec("d3", "Change Page?", 0, 8.4)
    c.proc("g1", "Display Selected Page of Logs", 1, 8.4)
    c.conn("g2", "1", 2, 8.4)
    c.e("d2", "d3", "No")
    c.e("d3", "g1", "Yes", out="r", into="l")
    c.e("g1", "g2", out="r", into="l")
    back_to_portal(c, "d3", 10.0)
